
spring:
  datasource:
    username: u_test
    password: u_test
    url: jdbc:oracle:thin:@172.21.118.88:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: o2o-view.shop-privider
server:
  port: 8081
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/