
server:
  port: 8080
spring:
  application:
    name: o2o-web-consumer
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

kaptcha:
  border: no
  textproducer:
    font:
      color: red
      size: 30
      name: Arial
    char:
      string: ACDEFHKPRSTWX345679
      length: 4
  image:
    width: 135
    height: 30
  noise:
    color: black



